/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useKeyboardControls } from '../hooks/useKeyboardControls'
import { useFrame } from '@react-three/fiber'

export default function Model({
  moveForward,
  moveBackward,
  moveLeft,
  moveRight,
  camerarotation,
}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ChicaT.gltf')
  const { actions } = useAnimations(animations, group)

  const dirRot = useRef(0)

const vrota = 0.3

  console.log(camerarotation)
  useEffect(() => {
    actions.OrcIdle.play();
  }, []);

  let animachoi = false;
  useFrame(() => {

  })
  if (moveForward && moveLeft) {
    if (dirRot.current > 2.2) {
      dirRot.current -= vrota
    } else if (dirRot.current < 2.2) {
      dirRot.current += vrota
    }
    // dirRot.current = 2.2
    animachoi = true
  } else if (moveForward && moveRight) {
    if (dirRot.current > 4.2) {
      dirRot.current -= vrota
    } else if (dirRot.current < 4.2) {
      dirRot.current += vrota
    }
    animachoi = true
  } else if (moveBackward && moveLeft) {
    animachoi = true
    if (dirRot.current > 0.5) {
      dirRot.current -= vrota
    } else if (dirRot.current < 0.5) {
      dirRot.current += vrota
    }
  } else if (moveBackward && moveRight) {
    animachoi = true
    if (dirRot.current > 5.8) {
      dirRot.current -= vrota
    } else if (dirRot.current < 5.8) {
      dirRot.current += vrota
    }
  } else if (moveForward) {
    animachoi = true
    if (dirRot.current > 3) {
      dirRot.current -= vrota
    } else if (dirRot.current < 3) {
      dirRot.current += vrota
    }
  } else if (moveBackward) {
    animachoi = true
    if (dirRot.current > 0) {
      dirRot.current -= vrota
    } else if (dirRot.current < 0) {
      dirRot.current += vrota
    }
  } else if (moveLeft) {
    animachoi = true
    if (dirRot.current > 1.5) {
      dirRot.current -= vrota
    } else if (dirRot.current < 1.5) {
      dirRot.current += vrota
    }
  } else if (moveRight) {
    animachoi = true
    dirRot.current = 4.5
    if (dirRot.current > 4.5) {
      dirRot.current -= vrota
    } else if (dirRot.current < 4.5) {
      dirRot.current += vrota
    }
  }
  if (actions.OrcIdle) {
    if (animachoi) {
      actions.Running.play();
    } else {
      actions.OrcIdle.play();
    }
  }
  return (
    <group ref={group} dispose={null}>
      <group rotation={[Math.PI / 2, 0, dirRot.current]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Ch46.geometry}
          material={materials['Ch46_body.001']}
          skeleton={nodes.Ch46.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/ChicaT.gltf')
