/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/running.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    // api.velocity.subscribe((v) => (velocity.current = v));
    console.log(actions)
    actions.running.play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Ch46.geometry}
          material={materials['Ch46_body.002']}
          skeleton={nodes.Ch46.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/running.gltf')
