/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/colgo.gltf')
  const { actions } = useAnimations(animations, group)
console.log(animations.colgo)
  useEffect(() => {
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.Hips} />
        <skinnedMesh
          geometry={nodes.Boy01_Body_Geo.geometry}
          material={materials.Boy01_Body_MAT}
          skeleton={nodes.Boy01_Body_Geo.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Boy01_Brows_Geo.geometry}
          material={materials.Boy01_Brows_MAT1}
          skeleton={nodes.Boy01_Brows_Geo.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Boy01_Eyes_Geo.geometry}
          material={materials.Boy01_Eyes_MAT1}
          skeleton={nodes.Boy01_Eyes_Geo.skeleton}
        />
        <skinnedMesh
          geometry={nodes.h_Geo.geometry}
          material={materials.Boy01_Mouth_MAT1}
          skeleton={nodes.h_Geo.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/colgo.gltf')
